spring:

  application:
    name: uni-minuto-task-mvc

  profiles:
    active: #spring.profiles.active#

  jmx:
    enabled: false

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    default-property-inclusion: non_null
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true
    serialization:
      indent_output: true
      write-bigdecimal-as-plain: true
      write-dates-as-timestamps: false

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/task_mvc?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: p4swr00t
    hikari:
      pool-name: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  liquibase:
    contexts: dev
    default-schema: task_mvc

  jpa:
    database: mysql
    show_sql: true
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.generate_statistics: false
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.boot.allow_jdbc_metadata_access: true
      hibernate.connection.provider_disables_autocommit: true
      # modify batch size as necessary
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_size: 10
      hibernate.query.in_clause_parameter_padding: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
    hibernate:
      ddl-auto: none

  messages:
    basename: i18n/messages

  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    mode: XHTML

  mvc:
    problemdetails:
      enabled: false
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 8090
